services:
  - type: web
    name: student-result-management
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: result-postgres-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: result-postgres-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: result-postgres-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: result-postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: result-postgres-db
          property: password
      - key: SESSION_COOKIE_SECURE
        value: "true"

databases:
  - name: result-postgres-db
    databaseName: result_db
    user: result_user
    plan: free
